Tsf 2747 repetere uker og dager i arbeidstid og omsorgstilbud
navikt/k9-punsj-frontend pull request #1231
Opened 2022-09-09 11:47 UTC by vebnor

2022-11-04 10:44 UTC, hallvardastark commented on cypress/e2e/fordeling/Fordeling.cy.js
> +    it('Midlertidig alene - kan navigere til eksisterende søknader', async () => {
trenger ikke async her

2022-11-04 10:51 UTC, hallvardastark commented on package.json
> +        "object-hash": "^3.0.0",
denne skal ligge under `dependencies`

2022-11-04 10:51 UTC, hallvardastark commented on src/app/components/buttons/Slett.tsx
> +            <Delete style={{ color: 'red' }} />
flytte til less 😄

2022-11-04 10:53 UTC, hallvardastark commented on src/app/components/buttons/buttons.less
> +    &:hover {
har denne knappen nå ingen fremheving ved tastaturnavigering?

2022-11-04 11:22 UTC, hallvardastark commented on src/app/containers/pleiepenger/SoknadKvittering/Komponenter/VisningAvPerioderSNSoknadKvittering.tsx
> +                <div key={uuidv4()}>
Dette er egentlig bad, men ser det var slik fra før

2022-11-04 11:30 UTC, hallvardastark commented on src/app/utils/timeUtils.ts
> +    } while (current.isSameOrBefore(dateRange.tom, 'day'));
fungerer denne `while` som den skal siden du har `;` etter?

2022-11-04 11:32 UTC, hallvardastark commented on src/app/utils/timeUtils.ts
> +    } while (current.isSameOrBefore(dateRange.tom, 'day'));
samme med denne `while`

2022-11-04 11:34 UTC, hallvardastark commented on src/stories/Introduction.stories.mdx
> +import { Meta } from '@storybook/addon-docs';
Hva er dette og svg-ene du inkluderer?

2022-11-04 11:34 UTC, hallvardastark requested changes
Se kommentarer

2022-11-04 12:26 UTC, vebnor commented on cypress/e2e/fordeling/Fordeling.cy.js
> +    it('Midlertidig alene - kan navigere til eksisterende søknader', async () => {
den feiler uten :(

2022-11-04 12:40 UTC, vebnor commented on src/app/components/buttons/buttons.less
> +    &:hover {
joda, ser den har en border

2022-11-04 12:43 UTC, vebnor commented on src/app/utils/timeUtils.ts
> +    } while (current.isSameOrBefore(dateRange.tom, 'day'));
Det er kopiert fra brukerdialog, så det er kode som har vært i bruk en stund i prod

2022-11-04 12:47 UTC, vebnor commented on src/stories/Introduction.stories.mdx
> +import { Meta } from '@storybook/addon-docs';
eksempelgreier fra historieboken. Fjerne det

2022-11-04 13:01 UTC, vebnor commented on src/app/components/buttons/Slett.tsx
> +            <Delete style={{ color: 'red' }} />
lå allerede i less også :D

2022-11-15 13:51 UTC, hallvardastark approved these changes

2022-11-16 08:56 UTC, merged