Lagt in slik att dersom en journalpost allerede er behandlet får man …
navikt/k9-punsj-frontend pull request #846
Opened 2021-09-18 11:45 UTC by eras-dev

…opp valg om att velge barn og kopiere journalpost.

Refaktorering: Dratt ut dropdown over barn och ifyllning av sökers barn i egen komponent for gjenbruk.

2021-09-20 13:19 UTC, vebnor commented on src/app/containers/pleiepenger/Fordeling/Komponenter/SokersBarn.tsx
> +        props.setIdentAction(finnesRiktigIdentIJournalposten && riktigIdentIJournalposten === JaNei.JA ? (journalpostident || '') : sokersIdent, event.target.value, identState.annenSokerIdent);
trenger man både `finnesRiktigIdentIJournalposten` og `riktigIdentIJournalposten`?

2021-09-20 13:24 UTC, vebnor commented on src/app/containers/pleiepenger/Fordeling/Komponenter/SokersBarn.tsx
> +        {(typeof erBarnUtdatert !== 'undefined' && !erBarnUtdatert || typeof erBarnUtdatert === 'undefined') && !!props.fellesState.hentBarnSuccess && typeof props.fellesState.barn !== 'undefined' &&
`typeof erBarnUtdatert !== 'undefined'` har ikke vært borti denne typen sjekker før. Holder det ikke sjekke om den er truthy?

2021-09-20 13:34 UTC, vebnor commented on src/app/containers/pleiepenger/Fordeling/Komponenter/SokersBarn.tsx
> +            <option key={uuidv4()} value={""}>
denne gir deg random ID hver gang, så den bør ikke brukes som key. Keyen må være stabil for at ikke React skal fjerne elementet og lage det på nytt hver gang

2021-09-20 13:34 UTC, vebnor commented on src/app/containers/pleiepenger/Fordeling/Komponenter/SokersBarn.tsx
> +                  <option key={uuidv4()} value={b.identitetsnummer}>
Her kan identitetsnummer være en fin key

2021-09-21 09:19 UTC, vebnor requested changes
la inn kommentarer og spørsmål

2021-09-21 10:11 UTC, eras-dev commented on src/app/containers/pleiepenger/Fordeling/Komponenter/SokersBarn.tsx
> +        {(typeof erBarnUtdatert !== 'undefined' && !erBarnUtdatert || typeof erBarnUtdatert === 'undefined') && !!props.fellesState.hentBarnSuccess && typeof props.fellesState.barn !== 'undefined' &&
Bytter till det. Har bara för vana att sjekke så att ikke propertyn er undefined innan jag försöker accessera den etter tidigare diskussioner :)

2021-09-21 14:25 UTC, vebnor approved these changes

2021-09-24 10:02 UTC, merged